### ISSUE TITLE
Shared libraries from "pip install pin" with Bazel

### ISSUE THREAD

**Issue by stephane-caron** [stephane-caron/bazel_pinocchio#1]
This issues is a follow-up to https://github.com/stack-of-tasks/pinocchio/issues/1715

Running the following command from this repo should execute the overview Python example from Pinocchio:

```console
$ bazel run //examples/python:overview-simple
```

Currently it results in:

```
  File "/.../examples/python/overview-simple.py", line 13, in <module>
    import pinocchio
ModuleNotFoundError: No module named 'pinocchio'
```

As far as I can tell, the reason for it is that Bazel populates ``sys.path`` as follows:

```
sys.path = [
    ...
    "bazel-out/k8-fastbuild/bin/examples/python/overview-simple.runfiles/pip_bazel_pinocchio/pypi__cmeel/cmeel.prefix/lib/python3.8/site-packages",
    ...
]
```

The problem is that the ``cmeel.prefix`` that contains pinocchio is located in ``pypi__pin`` rather than in ``pypi__cmeel``, so the sys.path is incomplete.

@nim65s how is ``cmeel.prefix`` added to ``sys.path`` in CMake Wheels?

**Comment by nim65s** [comment]
Hi,

cmeel sets its path through its `cmeel.pth` file ([ref](https://docs.python.org/3/library/site.html?highlight=.pth)). This expect `cmeel` and `pin` to be installed in the same prefix.

We can easily find a workaround by looking for the correct prefix in all paths, eg.:

```python
from cmeel.consts import CMEEL_PREFIX, SITELIB

for path in sys.path.copy():
    prefix = Path(path) / CMEEL_PREFIX / SITELIB
    if prefix.exists() and prefix not in sys.path:
        sys.path.append(prefix)
```

We can check that pinocchio is in sys.path with:
```python
for path in sys.path:
    if (Path(path) / "pinocchio").exists():
        print(f"pinocchio is in {path}")
        break
else:
    print("pinocchio is not in sys.path")
```
And I checked that on your example: running this function before the workaround yield nothing, but correctly shows the right folder after the workaround.

But still, I have the same error message. I don't understand that, maybe my test is wrong.

**Comment by nim65s** [comment]
Ok, my python skills are rusting: I was appending Path instances and not strings:
```python
from cmeel.consts import CMEEL_PREFIX, SITELIB

for path in sys.path.copy():
    prefix = Path(path) / CMEEL_PREFIX / SITELIB
    if prefix.exists() and prefix not in sys.path:
        sys.path.append(str(prefix))
```
Now this work.

I'll try to upstream this to cmeel. This will add a bit more delay for the interpreter to load, but it looks reasonable.

**Comment by stephane-caron** [comment]
Re-opening as, while ``sys.path`` is completed, we haven't got to the final import yet: 

```console
$ bazel run //examples/python:overview-simple
INFO: Analyzed target //examples/python:overview-simple (1 packages loaded, 2 targets configured).
INFO: Found 1 target...
Target //examples/python:overview-simple up-to-date:
  bazel-bin/examples/python/overview-simple
INFO: Elapsed time: 0.402s, Critical Path: 0.22s
INFO: 2 processes: 2 internal.
INFO: Build completed successfully, 2 total actions
INFO: Running command line: bazel-bin/examples/python/overview-simple
Traceback (most recent call last):
  File "~/.cache/bazel/_bazel_user/354ad6743c721a18cfadbbf4f8a51cea/execroot/bazel_pinocchio/bazel-out/k8-fastbuild/bin/examples/python/overview-simple.runfiles/bazel_pinocchio/examples/python/overview-simple.py", line 10, in <module>
    import pinocchio
ModuleNotFoundError: No module named 'pinocchio'
```

**Comment by stephane-caron** [comment]
I'm closing this issue now after updating the scope of this repository to C++ targets.

Since opening this issue, other challenges have surfaced with using `rules_python` between host (mostly x86) and Raspberry Pi (aarch64) targets, e.g. with NumPy. (See also [rules_pycross](https://github.com/jvolkman/rules_pycross).) I've switched gears to using Bazel for C++ targets and conda for Python, which has been satisfactory so far.
