### ISSUE TITLE
Build fails on Fedora

### ISSUE THREAD

**Issue by ubgk** [stephane-caron/bazel_pinocchio#7]
It is not an urgent issue, but I would like to document that the build fails on my Fedora environment, although it succeeds on Ubuntu.

A quick and dirty fix is to specify the `out_lib_dir` as `lib64` in the `cmake` rule for Pinocchio.

I believe `rules_foreign_cc` doesn't always play nicely with Bazel and breaks the hermeticity sometimes (we observe that the builds succeed when they should fail due to undocumented dependencies that `cmake` has).

Please refer to this [issue](https://github.com/bazelbuild/rules_foreign_cc/issues/325) for more details.

**Comment by stephane-caron** [comment]
Does it work if we add

```
        "CMAKE_INSTALL_LIBDIR": "lib",
```

to the rule's cache entries? (Source: https://github.com/conan-io/conan/issues/10393.)
